### ISSUE TITLE
CRNN can only run on GPU 0

### ISSUE THREAD

**Issue by sinterwong** [chenyangMl/crnn_libtorch#1]
I've done the same thing, but my libtorch model only runs on CPU 0. Have you had the same problem？

**Comment by chenyangMl** [comment]
> I've done the same thing, but my libtorch model only runs on CPU 0. Have you had the same problem？

sorry, i don't suffer same problem. I can use all mine CPU when testing with all this config.

**Comment by SinterCVer** [comment]
Sorry, the previous problem was misdescribed! My model runtime always takes up resources from GPU 0.
