### ISSUE TITLE
我也做了同样的事情，但是有一点问题想请教一下git主

### ISSUE THREAD

**Issue by Whatsetsthisend** [chenyangMl/crnn_libtorch#2]
但是我在加载torch::jit::load(modelFile)出现了严重的请求退出异常，想来想去可能是我pth转pt时候出现的一个warning有关，警告如下 TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert h == 1, "the height of conv must be 1"
他可能导致了我的crnn模型转换之后有错误加载失败，可否借git主的转换代码一看，或者是将我的代码发送给git主，期待您的回复谢谢

**Comment by Whatsetsthisend** [comment]
我已经解决了这个问题不劳费心谢谢

**Comment by chl916185** [comment]
请问您是怎么解决的呢，修改了模型的 if else嘛
@Whatsetsthisend

**Comment by chenyangMl** [comment]
> 我已经解决了这个问题不劳费心谢谢



> 但是我在加载torch::jit::load(modelFile)出现了严重的请求退出异常，想来想去可能是我pth转pt时候出现的一个warning有关，警告如下 TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> assert h == 1, "the height of conv must be 1"
> 他可能导致了我的crnn模型转换之后有错误加载失败，可否借git主的转换代码一看，或者是将我的代码发送给git主，期待您的回复谢谢

未能及时回复望见谅。
我复现了您说的这个转换的wrarning。这个warning是由于我crnn.py代码，forward函数里有一行 "assert h == 1, "the height of conv must be 1",导致torch.jit.trace的时候出现的，注释掉就没有了。
其次，不影响torch::jit::load()加载。
仅供参考。

**Comment by Whatsetsthisend** [comment]
后来我发现不是这个的问题，是在模型转换的时候我的crnn框架代码是写在另一个py中导入进来的，生成的pt我用压缩包工具打开查看发现model并不是直接在文件夹下导致了错误，应该将crnn的model代码和转换代码写在同一个py中，谢谢作者的回复。

**Comment by Whatsetsthisend** [comment]
> 请问您是怎么​​解决的呢，修改了模型的if else嘛
> @Whatsetsthisend

如果只是因为这个warning是像作者回复的一样注不注释都不影响，如果是导致了模型加载错误请看我上面的comments。

**Comment by Whatsetsthisend** [comment]
> > 我已经解决了这个问题不劳费心谢谢
> 
> > 但是我在加载torch :: jit :: load（modelFile）出现了严重的请求退出异常，想来想去可能是我pth转pt时候出现的一个警告有关，警告如下TracerWarning：将张量转换为Python布尔值可能导致跟踪不正确。我们无法记录Python值的数据流，因此该值将来会被视为常量。这意味着跟踪可能不会推广到其他输入！
> > assert h == 1，“转换高度必须为1” 
> > 他可能导致了我的crnn模型转换之后有错误加载失败，可否借gitgit的转换代码一看，或者是将我的代码发送给gitmain ，期待您的回复谢谢
> 
> 未能及时回复望见谅。
> 我复现了您说的这个转换的wrarning。这个警告是由于我crnn.py代码，向前函数里有一行“断言ħ== 1， “CONV的高度必须是1” ，导致torch.jit.trace的时候出现的，注释掉就没有了。
> 其次，不影响torch :: jit :: load（）加载。可以
> 参考。

还有一个问题请教一下，可以问一下git主的数据集吗，感觉我的模型都没有这么好的效果
