### ISSUE TITLE
请教一下，可以问一下git主的数据集吗，感觉我的模型都没有这么好的效果

### ISSUE THREAD

**Issue by Whatsetsthisend** [chenyangMl/crnn_libtorch#3]
教一下，可以问一下git主的数据集吗，感觉我的模型都没有这么好的效果

**Comment by chenyangMl** [comment]
数据主要是英文的扫描文档，做了很多的扩充。

**Comment by chenyangMl** [comment]
> 教一下，可以问一下git主的数据集吗，感觉我的模型都没有这么好的效果

数据主要是英文的扫描文档，然后做了很多的数据扩充。效果不好，个人觉得主要是数据量不够。
