### ISSUE TITLE
crnn pytorch源码来源

### ISSUE THREAD

**Issue by piaoliuping123** [chenyangMl/crnn_libtorch#4]
非常感谢您的杰出工作，请问您是参考哪个pytorch版本的crnn编写libtorch crnn，可以给出pytorch版本crnn网址链接吗？谢谢！

**Comment by chenyangMl** [comment]
> 非常感谢您的杰出工作，请问您是参考哪个pytorch版本的crnn编写libtorch crnn，可以给出pytorch版本crnn网址链接吗？谢谢！

参考这个工程的crnn https://github.com/meijieru/crnn.pytorch
